### ISSUE TITLE
Geolocation off on a lake

### ISSUE THREAD

**Issue by maxlavoie** [AugustT/shiny_geolocation#1]
thanks for the code! I built a shiny app using your code found in accuracy_and_dynamic. The geolocation was +- 15-20 m accurate when using the app from a house or a building. 

But the geolocation was way off when we using a cellphone on a lake. Any suggestions on why this happening. Thanks

edit: I don't know if this could help but using this https://github.com/M165437/Leaflet.AccuratePosition gave me very good accuracy on the same lake.
Martin

**Comment by AugustT** [comment]
The location data comes from the phone so I'm not sure how/if this could be improved from the shiny app side of things.
