### ISSUE TITLE
Include compass value

### ISSUE THREAD

**Issue by dewalex** [AugustT/shiny_geolocation#3]
@AugustT  Thanks so much for posting this, it has been a real big help for me.  I am trying however, to expand on what you have done and add in a compass value (the alpha value of the phone), so that I can point my location icon on my map to the area that i want to navigate to in the field.  
I am struggling to get this to work on Shiny, however.  Would you be able to help?  

Here is what I've been working off of:

```
$(document).ready(function () {
function handleOrientation(event) {
  var absolute = event.absolute;
  var alpha    = event.alpha;
  var beta     = event.beta;
  var gamma    = event.gamma;

   console.log(event);
	Shiny.onInputChange("bearing", alpha);
}

window.addEventListener("deviceorientation", handleOrientation, true);

     });
```

**Comment by AugustT** [comment]
@kazlauskis do you have any java for the compass we could use?

**Comment by kazlauskis** [comment]
We have this ancient app for [recording lichens](http://www.apis.ac.uk/lichen-app/main) that use a compass - go to Record -> Trunk 1. 

Here is the code for it: https://github.com/NERC-CEH/lichen-app/blob/83afa27b3ae1547903a61e787ab2d56197556200/THEME_SOURCE/scripts/src/app/compass.js#L7

**Comment by dewalex** [comment]
@kazlauskis Thanks for posting that. 
That compass doesn't work for me.  I am using an iPhone 7.  I assume things have changed and other calls have to be made now?

**Comment by kazlauskis** [comment]
I have tried [this one]( https://dev.to/gigantz/real-compass-on-mobile-browsers-with-javascript-3emi
) on iOS just now and it has worked 🧭 [WEB DEMO HERE](https://idzgd.csb.app/)

**Comment by dewalex** [comment]
@kazlauskis Thanks for finding the article!  That compass demo does indeed work on my phone, but doesn't work on Chrome, even when I simulate an alpha value, so it makes it very hard to test.  I can't get a reading on it.  
I know next to nothing of JavaScript, so there could be an issue with the code that I modified to try to get a Shiny input value from it.  Would you be able to see if you can get this to work?  (the button that I am pressing to initalize is called ```currentlocationfab5```)

```
$(document).ready(function () {

//const compassCircle = document.querySelector(".compass-circle");
//const startBtn = document.querySelector("");
//const myPoint = document.querySelector(".my-point");
//let compass;

const isIOS = !(
  navigator.userAgent.match(/(iPod|iPhone|iPad)/) &&
  navigator.userAgent.match(/AppleWebKit/)
);

function init() {
  document.getElementById("currentlocationfab5").addEventListener("click", startCompass);
Shiny.onInputChange("didinit", true)
}

function startCompass() {
  if (isIOS) {
    DeviceOrientationEvent.requestPermission()
      .then((response) => {
        if (response === "granted") {
          window.addEventListener("deviceorientation", handler, true);
        } else {
          alert("has to be allowed!");
        }
      })
      .catch(() => alert("not supported"));
  } else {
    window.addEventListener("deviceorientation", handler, true);
  }
}

function handler(e) {
  var compass = e.webkitCompassHeading || Math.abs(e.alpha - 360);

Shiny.onInputChange("bearing", compass);
  //compassCircle.style.transform = `translate(-50%, -50%) rotate(${-compass}deg)`;
}

init();
 });
```

**Comment by kazlauskis** [comment]
Try the code from this one, it works on Android Chrome for me: https://whatwebcando.today/device-position.html

**Comment by dewalex** [comment]
Ok, so I figured out that the code above works except for the if(isIOS) part.  If I just put if(1==1) on that section and then use an iPhone, it will work (that makes it not work on other devices though, of course).

**Comment by dewalex** [comment]
@kazlauskis I'll look into it.  Thanks!

**Comment by AugustT** [comment]
@dewalex if you get a reliable solution let me know, it would be great to add it here as a resource for others

**Comment by dewalex** [comment]
This works for only iOS, since I couldn't get the if(isIOS) part of the function to work, so I just changed it to 1==1 for now.  

```
$(document).ready(function () {

//const compassCircle = document.querySelector(".compass-circle");
//const startBtn = document.querySelector("");
//const myPoint = document.querySelector(".my-point");
//let compass;

const isIOS = !(
  navigator.userAgent.match(/(iPod|iPhone|iPad)/) &&
  navigator.userAgent.match(/AppleWebKit/)
);

function init() {
document.getElementById("currentlocationfab6").addEventListener("click", startCompass);  
document.getElementById("currentlocationfab5").addEventListener("click", startCompass);

Shiny.onInputChange("didinit", true)
}

function startCompass() {
  if (1==1) {
    DeviceOrientationEvent.requestPermission()
      .then((response) => {
        if (response === "granted") {
          window.addEventListener("deviceorientation", handler, true);
        } else {
          alert("has to be allowed!");
        }
      })
      .catch(() => alert("not supported"));
  } else {
    window.addEventListener("deviceorientation", handler, true);
  }
}

function handler(e) {
  var compass = e.webkitCompassHeading || Math.abs(e.alpha - 360);
 var alpha = e.alpha
Shiny.onInputChange("bearing", compass);
}

init();
 });
```
